### PR TITLE
Git clone in Makefile and HTPC-Manager to HTPC Manager

### PR DESCRIPTION
**Pull request by Decipher**
Changes as per https://github.com/SynoCommunity/spksrc/pull/689 as well as naming change and path cleanup.

### CODE REVIEW

**Comment by cytec** [comment]
I think you still Need git in PATH so one can use the web-updater

**Comment by Decipher** [comment]
I thought that might be why it was there, but I tested with my code as per this pull request and the git update worked perfectly.

**Comment by Decipher** [comment]
My understanding is that this PATH is only relevant for the installation or the triggering of the start/stop/etc, and the location of GIT for the updating inside the app is managed inside the app, and it's clearly smart enough to find it itself.

**Comment by cytec** [comment]
PATH gets exportet on every start so, that the program knows where to look for binarys i know you can give a custom path to the git binary inside the app itself but if its in the PATH variable that should not bee needed

**Comment by Decipher** [comment]
As I said though, without the PATH, and without adjusting the settings inside the app, the GIT update feature inside the app worked first go.

**Pull request merged**
